backend:
  name: github # Netlify’s Git Gateway connects to Git provider’s API
  repo: zhixiangteoh/thenewspanels-netlify
  branch: master # Branch to update (master by default)
  site-domain: thenewspanels-netlify.netlify.com

media_folder: "images/comics" # Folder where user uploads files

# publish_mode: editorial_workflow # Enable drafts

collections:
  - name: "comic" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Comic" # Used in the UI, ie.: "New Post"
    folder: "_comics" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Layout", name: "layout", widget: "hidden", default: "comic", required: true}
      - {label: "Comic Name", name: "name", description: "The name of the comic used for the window title, accessibility/screen readers, etc.", widget: "string", tagname: "h1", default: "Untitled Comic", required: true}
      # - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", required: true}
      - {label: "Comic Number", name: "number", description: "The 'number' of the comic, e.g. 'the 11th comic added to the site'. Used to identify the comic.", widget: "string", default: "1", required: true}
      - {label: "Comic Hash", name: "title", description: The "number" of the comic again, but this time with leading zeroes to make it 6 characters long. Used to sort/order comics.", widget: "string", default: "000001", required: true}
      - label: "Comic Panels"
        name: "images"
        description: "The images to display in the comic."
        widget: "list"
        field: 
          - {label: "Image", name: "image", widget: "image"}
  - name: "page" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Page" # Used in the UI, ie.: "New Post"
    folder: "_pages" # The path to the folder where the documents are stored
    sort: "title:asc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Layout", name: "layout", widget: "hidden", default: "page", required: true}
      - label: "Page Layout"
        name: "grid"
        description: "The predefined 'newspaper-like' template to place the comics in when viewed on desktop."
        widget: "number"
        valueType: "int"
        min: 0
        step: 1
        default: 1
        required: true
      - {label: "Page Title", name: "name", description: "The title of the page to be used by the tab/window, search engines, sharing the link on social media, etc.", widget: "string", required: true}
      - {label: "Page Number", name: "number", description: "The number of the page, e.g. 'this is the 11th page I've created'. Used to identify pages.", widget: "string", default: "1", required: true}
      - {label: "Page Hash", name: "title", description: "The number of the page again, but this time with leading zeros to make it 6 characters. Used to sort/order pages.", widget: "string", required: true}
      - label: "Comic Number"
        name: "start"
        description: "The number of the 'start' comic that should be the first comic on the page. E.g. the first page should use '1'. If the first page contains 10 comics, then the second page would start with comic '11', etc."
        widget: "number"
        valueType: "int"
        min: 1
        max: 999999
        step: 1
        default: 1
        required: true
  # - name: "comic" # Used in routes, ie.: /admin/collections/:slug/edit
  #   label: "Comic" # Used in the UI, ie.: "New Post"
  #   folder: "_comics" # The path to the folder where the documents are stored
  #   sort: "date:desc" # Default is title:asc
  #   create: true # Allow users to create new documents in this collection
  #   slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
  #   fields: # The fields each document in this collection have
  #     - {label: "Layout", name: "layout", widget: "hidden", default: "comic", required: true}
  #     - {label: "Comic Name", name: "name", description: "The name of the comic used for the window title, accessibility/screen readers, etc.", widget: "string", tagname: "h1", default: "Untitled Comic", required: true}
  #     # - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", required: true}
  #     - {label: "Comic Number", name: "number", description: "The 'number' of the comic, e.g. 'the 11th comic added to the site'. Used to identify the comic.", widget: "string", default: "1", required: true}
  #     - {label: "Comic Hash", name: "title", description: The "number" of the comic again, but this time with leading zeroes to make it 6 characters long. Used to sort/order comics.", widget: "string", default: "000001", required: true}
  #     - label: "Comic Panels"
  #       name: "images"
  #       description: "The images to display in the comic."
  #       widget: "list"
  #       fields: 
  #         - label: "Image"
  #           name: ""
  #           widget: "image"