backend:
  name: github # Netlify’s Git Gateway connects to Git provider’s API
  repo: zhixiangteoh/thenewspanels-netlify
  branch: master # Branch to update (master by default)
  site-domain: thenewspanels-netlify.netlify.com

media_folder: "images" # Folder where user uploads files

publish_mode: editorial_workflow # Enable drafts

collections:
  - name: "comic" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Comic" # Used in the UI, ie.: "New Post"
    folder: "_comics" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Layout", name: "layout", widget: "hidden", default: "comic"}
      - {label: "Comic Name", name: "name", description: "The name of the comic used for the window title, accessibility/screen readers, etc.", widget: "string", tagname: "h1", default: "Untitled Comic"}
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss"}
      - {label: "Comic Number", name: "number", description: "The 'number' of the comic, e.g. 'the 11th comic added to the site'. Used to identify the comic.", widget: "string", default: "1"}
      - {label: "Comic Hash", name: "title", widget: "string", default: "000001"}
      - label: "Comic Panels"
        name: "images"
        description: "The images to display in the comic."
        widget: "list"
        fields: 
          - label: "Image"
            name: "url"
            widget: "image"
          - label: "Caption"
            name: "caption"
            widget: "string"
          